# Generated by Django 4.2.7 on 2023-11-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockVisualizer', '0002_stockdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
